---
title: "Visualization"
output: github_document
---

#Visualization

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

```{r}
weather_df
```

let's make a ggplot

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax)) + 
  geom_point()
```

I always like the dataframe fisrt.

```{r}
ggp_temp_scatterplot = 
  weather_df|>
  ggplot(aes(x= timn, y = tmas))+
  geom_point()

weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name),alpha = .25)+
  geom_smooth(se = FALSE)
```

The aesthetics are up to you

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_smooth(se = FALSE)
```

Show faceting

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(cols = vars(name))
```

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```


make a plot of central park 
```{r}
weather_df |>
  filter(name == "CentralPark_NY")|>
  mutate(
    tmax = tmax *(9/5)+32,
    tmin = tmin *(9/5)+32
  )|>
  ggplot(aes(x = tmax, y= tmin))+
  geom_point()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin)) + 
  geom_hex()
```

## Univariate plots

```{r}
weather_df |>
  ggplot(aes(x = tmax))+
  geom_histogram()
```


```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram() +
  facet_grid(.~name)
```

Density plots are great !!

```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_density(alpha = 0.25)
```


Boxplots

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmax))+
  geom_boxplot()
```


Violin

```{r}
weather_df |>
  ggplot(aes(x = name, y = tmax))+
  geom_violin()
```


Bridge plots...

```{r}
weather_df |>
  ggplot(aes(y = name, x = tmax)) +
  geom_density_ridges()
```









